services:
  - type: web
    name: persian-ocr
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
